version: 0.0
os: linux
files:
  - source: userpreference/target/userpreference.jar  # Use the new name
    destination: /home/ec2-user/deploy
hooks:
  BeforeInstall:
    - location: userpreference/prescript.sh
      timeout:  3000
      runas: root
  AfterInstall:
    - location: userpreference/postscript.sh 
      timeout: 3000
      runas: root
